site_name: OSG School 2023
site_url: https://osg-htc.org/user-school-2023/
repo_name: null
theme:
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.png

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OSGUserSchool
      name: OSG School on Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/OSGUserSchool
      name: OSG School on Facebook

nav:
  - Home:                           index.md
  - Schedule:                       schedule.md
  - Health Guidelines:              health.md
  - Logistics:
    - General information:          logistics/index.md
    - Travel:
      - Travel planning:            logistics/travel-planning.md
      - Travel Inc form tips:       logistics/travel-form.md
      - Local transportation:       logistics/local-transportation.md
      - Travel advice:              logistics/travel-advice.md
    - Visa requirements:            logistics/visas.md
    - Hotel information:            logistics/hotel.md
    - School location:              logistics/location.md
    - Meal information:             logistics/meals.md
    - Dining options:               logistics/dining.md
    - Fun activities:               logistics/fun.md
  - Materials:
    - Overview:                     materials/index.md
    - HTC Exercises:
      - Exercise 1.1:               materials/htcondor/part1-ex1-login.md
      - Exercise 1.2:               materials/htcondor/part1-ex2-commands.md
      - Exercise 1.3:               materials/htcondor/part1-ex3-jobs.md
      - Exercise 1.4:               materials/htcondor/part1-ex4-logs.md
      - Exercise 1.5:               materials/htcondor/part1-ex5-request.md
      - Exercise 1.6:               materials/htcondor/part1-ex6-remove.md
      - Bonus Exercise 1.7:         materials/htcondor/part1-ex7-compile.md
      - Bonus Exercise 1.8:         materials/htcondor/part1-ex8-queue.md
      - Bonus Exercise 1.9:         materials/htcondor/part1-ex9-status.md
      - Exercise 2.1:               materials/htcondor/part2-ex1-files.md
      - Exercise 2.2:               materials/htcondor/part2-ex2-queue-n.md
      - Exercise 2.3:               materials/htcondor/part2-ex3-queue-from.md
      - Exercise 2.4:               materials/htcondor/part2-ex4-queue-matching.md 
    - OSG Exercises:
      - Exercise 1.1:               materials/osg/part1-ex1-submit-refresher.md
      - Exercise 1.2:               materials/osg/part1-ex2-login-scp.md
      - Exercise 1.3:               materials/osg/part1-ex3-submit-osg.md
      - Exercise 1.4:               materials/osg/part1-ex4-hardware-diffs.md
      - Exercise 1.5:               materials/osg/part1-ex5-software-diffs.md
    - Troubleshooting Exercises:
      - Exercise 1.1:               materials/troubleshooting/part1-ex1-troubleshooting.md
      - Exercise 1.2:               materials/troubleshooting/part1-ex2-job-retry.md
    - Software Exercises: 
      - Exercise 1.1:               materials/software/part1-ex1-run-apptainer.md
      - Exercise 1.2:               materials/software/part1-ex2-apptainer-jobs.md
      - Exercise 1.3:               materials/software/part1-ex3-docker-jobs.md
      - Exercise 1.4:               materials/software/part1-ex4-apptainer-build.md
      - Exercise 1.5:               materials/software/part1-ex5-pick-an-option.md
      - Exercise 2.1:               materials/software/part2-ex1-build-executable.md
    - Choose Your Own Software Exercises: 
      - Exercise 3.1:               materials/software/part3-ex1-apptainer-recipes.md
      - Exercise 3.2:               materials/software/part3-ex2-docker-build.md
      - Exercise 4.1:               materials/software/part4-ex1-download.md
      - Exercise 4.2:               materials/software/part4-ex2-wrapper.md
      - Exercise 4.3:               materials/software/part4-ex3-arguments.md
      - Exercise 5.1:               materials/software/part5-ex1-prepackaged.md
      - Exercise 5.2:               materials/software/part5-ex2-python.md
      - Exercise 5.3:               materials/software/part5-ex3-conda.md
      - Exercise 5.4:               materials/software/part5-ex4-compiling.md

